# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eafe86aed82cddb49a1eb2cc2733392b6aaced266956eda8076fe219a444124d1030f3aeaef3c09de7d436c1b409b66c5db7deeaffe0fdfbf218249636e33da4

test:
  secret_key_base: 178c891a074c74b3c21bfa84f8d134638f5e833c9582127d3b2f4139ec10728a21bfc1996fa043d9abc16a6bce95048276f993791a85a3a79b29a29da6f5b525

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
